language: python
python:
  - "3.6.0"

install:
  - pip install -r requirements.txt
  - pip install coverage
  
script: true
  - python test_app.py
  
after_script:
  - coveralls

after_success:
  - codecov
