language: python
python:
  - 3.6.0
env: FLASK_APP FLASK_ENV=development

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest
  - pip install coverage
  
script: true
  - coverage erase
  - coverage run -m apiv1.test_app 
  
after_script:
  - coveralls

after_success:
  - codecov --token=c886e1a6-eb39-4ea0-91cb-0dfcdfbf2190
